# fly.toml app configuration file generated for cnsplus on 2026-05-26T10:55:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cnsplus'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  Api__BaseUrl = 'https://api.comicplus.net'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
